name: Node.js Package (Dev)

on:
  push:
    branches:
      - dev

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm run build

      - run: |
          VERSION=$(node -p "require('./package.json').version + '-dev.' + Date.now()")
          npm version $VERSION --no-git-tag-version

      - run: npm whoami
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}

      - run: npm publish --tag dev --access public
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
